M48
; DRILL file KiCad 10.0.5 date 2026-08-08T18:07:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-08T18:07:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X2.61Y-37.4
X8.39Y-37.4
T2
X3.5Y-4.0
X4.0Y-76.0
X56.0Y-76.0
X56.5Y-4.0
M30
