M48
; DRILL file KiCad 10.0.5 date 2026-08-08T09:27:43
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-08T09:27:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X2.9Y-37.11
X2.9Y-42.89
T2
X4.0Y-4.0
X4.0Y-76.0
X56.0Y-4.0
X56.0Y-76.0
M30
